export const MANAGER_REGISTER_REQUEST='MANAGER_LOGIN_REQUEST'
export const MANAGER_REGISTER_FAIL='MANAGER_LOGIN_FAIL'
export const MANAGER_REGISTER_SUCCESS='MANAGER_LOGIN_SUCCESS'
export const MANAGER_LOGOUT='MANAGER_LOGOUT'